# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

beta_PPL_loop <- function(R1_j, R2_j, z1_j, z2_j, delta1_j, delta2_j, exp_eta1, exp_eta2, beta1_scr, beta2_scr, r_scr, beta1_inf, beta2_inf, r_inf, beta1_r_inf, beta2_r_inf, m, eta1, eta2) {
    invisible(.Call(`_BivPPL_beta_PPL_loop`, R1_j, R2_j, z1_j, z2_j, delta1_j, delta2_j, exp_eta1, exp_eta2, beta1_scr, beta2_scr, r_scr, beta1_inf, beta2_inf, r_inf, beta1_r_inf, beta2_r_inf, m, eta1, eta2))
}

beta_PPL_loop_huge <- function(R1_j, R2_j, z1_j, z2_j, delta1_j, delta2_j, exp_eta1, exp_eta2, beta1_scr, beta2_scr, r_scr, beta1_inf, beta2_inf, r_inf, beta1_r_inf, beta2_r_inf, m, N, eta1, eta2) {
    invisible(.Call(`_BivPPL_beta_PPL_loop_huge`, R1_j, R2_j, z1_j, z2_j, delta1_j, delta2_j, exp_eta1, exp_eta2, beta1_scr, beta2_scr, r_scr, beta1_inf, beta2_inf, r_inf, beta1_r_inf, beta2_r_inf, m, N, eta1, eta2))
}

